apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  label: 
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-prod
      label:
        app: myapp
        type: front-end
      spec:
        containers:
          - name: nginx-controller
            image: nginx
  replicas: 3
  


